# Use an official Node.js runtime as the base image
FROM node:20.18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Copy the entire project to the working directory
COPY . .

# Install dependencies
RUN npm install

# Expose the default vite port
EXPOSE 5173

# Start the Next.js app
CMD ["npm", "run", "dev"]
