# # Use an official Node.js runtime as the base image
# FROM node:20.18-alpine

# # Set working directory
# WORKDIR /app

# # Copy package.json and package-lock.json
# COPY package*.json ./

# # Copy the entire project to the working directory
# COPY . .

# # Install dependencies
# RUN npm install

# # Expose the default vite port
# EXPOSE 5173

# # Start the Next.js app
# CMD ["npm", "run", "dev"]

# -------- Stage 1: Build --------
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build


# -------- Stage 2: Serve --------
FROM nginx:alpine

# Remove default nginx static files
RUN rm -rf /usr/share/nginx/html/*

# Copy built app from previous stage
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]